### ISSUE TITLE
feature request, implement helpername from aaa_hired_helper

### ISSUE THREAD

**Issue by Sie-vo** [Bobster82/FS22_VehicleInfo#10]
Can you implement the helpernames from hired helper tool?

**Comment by Bobster82** [comment]
I think that is posible. I dont know when I be able to work on it, as I have some other priorities.
I will add it to the list to check out

**Comment by Bobster82** [comment]
I was looking into that mod and it just replaces helper a to a name... So you want to see if its a helper for example, instead of 'H', 'HelperName' ('Patty') ...
Why do you want to see these names? Is it if a helper is finished with a job you know what helper? You see already if its a helper with 'H' or 'AD' or (currently not working yet) 'CP' and if its done, the status changes to stopped.

I dont really see an added value to it. Maybe if you can explain more why you want it?
